name: Build Flask Docker App

on:
  push:
    branches: [ live_website ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v3

      - name: 🐍 Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: 🐳 Build Docker image
        run: docker build -t jmarcelocarvalho-app .
